### PR TITLE
Copy missing icudtl.dat

### PR DESCRIPTION
**Pull request by jld3103**

### CODE REVIEW

**Comment by jld3103** [comment]
I see you already fixed it :)

**Comment by csnewman** [comment]
`src/third_party/icu/flutter/icudtl.dat` is the correct icudtl.dat to use, its about 1mb vs the 10mb created in the output directory.

I have fixed this in master, however it should be unneeded, as the flutter binaries already contain icudtl.dat (the symbols are exported). I have included the .dat anyways.

**Comment by jld3103** [comment]
@csnewman The icudtl.dat file isn't included in the current release

**Comment by csnewman** [comment]
I've checked a few myself, they seem to contain the icudtl.dat file. Any specific release that doesn't?

I am tempted to remove the icudtl.dat file from each of the archives and instead place it in its own zip. As its not really related to any release (and isn't needed by them).

**Comment by jld3103** [comment]
Ok somehow I oversaw the file

**Pull request closed without merging**
